config/routes.rb
Widgetexample::Application.routes.draw do

  devise_for :users

  resources :journalists

  match "custom_design" => "site#custom_design"
  match "invisible_widget" => 'site#invisible_widget'
  
  root :to => 'journalists#index'

end

app/models/user.rb
class User
  include Mongoid::Document

  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :uncoverage_id, :photo_url, :biography, :role

  field :first_name
  field :last_name

  field :uncoverage_id
  field :photo_url

  field :biography

  field :role

  scope :journalists, -> { where(role: "journalist") }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  def full_name
    "#{first_name} #{last_name}" if first_name && last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/journalists_controller.rb
class JournalistsController < ApplicationController
  layout "site"
  def index
    @journalists = User.journalists
  end

  def show
    @journalist = User.find(params[:id])
  end
end

app/controllers/site_controller.rb
class SiteController < ActionController::Base
  protect_from_forgery
  layout "site"

  def invisible_widget
  end

  def custom_design
    @journalist_ids = if Rails.env.production?
      User.journalists.limit(3).map(&:uncoverage_id)
    else
      ["538232c25679610408210000", "539308b15679618ca00a0000", "5384cb2b5679612ad8260000"]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/journalists/index.html.erb
<div class="journalists">
  <!-- <h1>Journalists</h1> -->
  <% @journalists.each do |j| %>
    <div class="journalist">
      <h2><%= j.full_name %></h2>
      <%= link_to 'go to profile →', journalist_path(j) %>
      <div class="photo"><%= image_tag j.photo_url %></div>
      <div class="bio"><%= j.biography %></div>
    </div>
  <% end %>
</div>

app/views/journalists/show.html.erb
<div class="journalist">
  <%= link_to '← back to the list', journalists_path %>
  <h1><%= @journalist.full_name %></h1>
  <div class="photo"><%= image_tag @journalist.photo_url %></div>
  
  <iframe class="uncoverage_widget" id="<%= @journalist.uncoverage_id %>" data-custom-css="http://<%= Rails.env.production? ? 'widgetexample.herokuapp.com' : 'localhost:3001' %>/custom_uncoverage_widget_black.css" src="//<%= Rails.env.production? ? 'www.uncoverage.com' : 'localhost:3000' %>/widget?journalist_id=<%= @journalist.uncoverage_id %>&amount=1000"/></iframe>
  <h2><%= @journalist.first_name %>'s biography</h2>
  <% 10.times do %>
    <div class="bio"><%= @journalist.biography %></div>
  <% end %>
  <script src="//<%= Rails.env.production? ? 'www.uncoverage.com' : 'localhost:3000' %>/assets/widget/widget_code.js"></script>
</div>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Widgetexample</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <% if @mobile_device %>
    <%= stylesheet_link_tag "mobile", :media => "all" %>
  <% end %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="//use.typekit.net/yfm8mdo.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
</head>
<body>
  <div id="header">
    <h1>The News Site</h1>
  </div>
  <div id="main">
    <%= yield %>
  </div>
</body>
</html>

app/views/site/custom_design.html.erb
<div class="widget_examples">
  <script src="//<%= Rails.env.production? ? 'www.uncoverage.com' : 'localhost:3000' %>/assets/widget/widget_code.js"></script>

  <h1>Customizing widget design</h1>

  <p>You can easily customise widget design, providing your own css file by adding the <b>data-custom-css</b> attribute to the iframe, the value should be a link to a css file</p>

  <div class="code_example">
    <%= "<iframe class='uncoverage_widget' id='#{ @journalist_ids[0] }' data-custom-css='http://#{ Rails.env.production? ? 'widgetexample.herokuapp.com' : 'localhost:3001' }/custom_uncoverage_widget.css' src='//#{ Rails.env.production? ? 'www.uncoverage.com' : 'localhost:3000' }/widget?journalist_id=#{ @journalist_ids[0] }&amp;amount=1000'></iframe>"%>
  </div>
  <div class="widget_example">
    <iframe class="uncoverage_widget" id="<%= @journalist_ids[0] %>" data-custom-css="http://<%= Rails.env.production? ? 'widgetexample.herokuapp.com' : 'localhost:3001' %>/custom_uncoverage_widget.css" src="//<%= Rails.env.production? ? 'www.uncoverage.com' : 'localhost:3000' %>/widget?journalist_id=<%= @journalist_ids[0] %>&amp;amount=1000"/></iframe>
  </div>

  <div class="code_example">
    <%= "<iframe class='uncoverage_widget' id='#{ @journalist_ids[1] }' data-custom-css='http://#{ Rails.env.production? ? 'widgetexample.herokuapp.com' : 'localhost:3001' }/custom_uncoverage_widget_black.css' src='//#{ Rails.env.production? ? 'www.uncoverage.com' : 'localhost:3000' }/widget?journalist_id=#{ @journalist_ids[1] }&amp;amount=1000'></iframe>"%>
  </div>
  <div class="widget_example">
    <iframe class="uncoverage_widget" id="<%= @journalist_ids[1] %>" data-custom-css="http://<%= Rails.env.production? ? 'widgetexample.herokuapp.com' : 'localhost:3001' %>/custom_uncoverage_widget_black.css" src="//<%= Rails.env.production? ? 'www.uncoverage.com' : 'localhost:3000' %>/widget?journalist_id=<%= @journalist_ids[1] %>&amp;amount=1000"/></iframe>
  </div>
</div>

app/views/site/invisible_widget.html.erb
<div id="container">
  <header>
    <%= image_tag "http://s.huffpost.com/images/v/logos/bpage/politics.gif" %>
  </header>

  <section>
    <h1>Stephen Colbert To IRS: Let Me Make Fun Of 'Dark Money' And Super PACs Some More</h1>
    
    <%= image_tag "http://i0.huffpost.com/gen/1651947/thumbs/n-STEPHEN-COLBERT-SUPER-PAC-large570.jpg", class: "photo" %>

    <p>WASHINGTON -- Comedian Stephen Colbert, whose gags have pointed out the absurdity of U.S. campaign finance laws since the Supreme Court's 2010 Citizens United ruling, asked the IRS Thursday for permission to testify on proposed rules governing the political activity of social welfare nonprofits.</p>

    <p>Colbert said in a comment filed with the IRS that the proposed rules "raise serious constitutional and legal issues" for social welfare nonprofits. These organizations have become known as "dark money" groups, because they allow political operatives to spend money on electoral activity without having to disclose donors.</p>

    <p>Colbert in 2011 ran segments on his Comedy Central show "The Colbert Report" exposing campaign finance absurdities through the creation of his own super PAC -- Americans for a Better Tomorrow, Tomorrow -- and a social welfare nonprofit. The Huffington Post ran a five-part series on Colbert's campaign finance exploits.</p>

    <p>Colbert officially retired his super PAC in 2012 and donated the funds raised by both organizations to two campaign finance watchdog groups, the Campaign Legal Center, founded by Colbert's lawyer Trevor Potter, and the Center for Responsive Politics.</p>

    <p>The proposed rules have attracted a whopping 143,635 comments to the IRS, with both tea party and progressive groups mobilizing supporters. Campaign finance reform supporters also have flooded the IRS with comments urging it to set a stringent and clear limit on the amount of electoral activity these groups are allowed. The Huffington Post previously examined the regulations here.</p>

    <p>Colbert's position on the lengthy and complicated proposed rules is not entirely clear. His letter simply states, "The Proposed Regulations raise serious constitutional and legal issues for Colbert Super PAC SHH Institute and other entities like it, which seek to make America a better place. I request the opportunity to discuss these issues in detail through oral testimony at a public hearing related to the Proposed Regulations."</p>
  </section>
</div>

<!-- Start of Uncoverage widget -->
<script src="//localhost:3000/assets/widget/widget_integration_code.js"></script>
<iframe id="integration_widget" src="//www.uncoverage.com/integration_widget?journalist_id=5355b0050b4a45b11d000001" style="display: none;"/></iframe>

<!-- end of Uncoverage widget -->

app/views/site/statement.html.erb
<!-- Start of Uncoverage widget (part 1/2) -->
<div id="modal">
  <div class="content">
    <div class="body"></div>
    <div class="footer">
      <button type="button">
        Close
      </button>
    </div>
  </div>
  <div id="modal-backdrop"></div>
</div>
<!-- End of Uncoverage widget -->


<div id="container">
  <header>
    <%= image_tag "http://s.huffpost.com/images/v/logos/bpage/politics.gif" %>
  </header>

  <nav></nav>

  <section class="journalist">

    <%= image_tag "http://s.huffpost.com/contributors/paul-blumenthal/headshot.jpg", class: "journalist_photo" %>
    <span class="name">Paul Blumenthal Become a fan</span>
      
    <!-- Start of Uncoverage widget -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://alpha.uncoverage.com/assets/widget/widget_modal.css">
    <script src="http://alpha.uncoverage.com/assets/widget/widget_code.js"></script>

    <iframe id="widget" src="http://alpha.uncoverage.com/widget?journalist_id=5355b0050b4a45b11d000001&amount=100" style="border: 0; width: 420px; height: 230px;"/></iframe>

    <!-- end of Uncoverage widget -->


    <!-- Start of Uncoverage widget -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://localhost:3000/assets/widget/widget_modal.css">
    <script src="http://localhost:3000/assets/widget/widget_code.js"></script>

    <iframe id="widget" src="http://localhost:3000/widget?journalist_id=537e0cc856796146d0120000&amount=100" style="border: 0; width: 420px; height: 230px;"/></iframe>

    <!-- end of Uncoverage widget -->

    

    

  <section>
    <h1>Stephen Colbert To IRS: Let Me Make Fun Of 'Dark Money' And Super PACs Some More</h1>
    
    <%= image_tag "http://i0.huffpost.com/gen/1651947/thumbs/n-STEPHEN-COLBERT-SUPER-PAC-large570.jpg", class: "photo" %>

    <p>WASHINGTON -- Comedian Stephen Colbert, whose gags have pointed out the absurdity of U.S. campaign finance laws since the Supreme Court's 2010 Citizens United ruling, asked the IRS Thursday for permission to testify on proposed rules governing the political activity of social welfare nonprofits.</p>

    <p>Colbert said in a comment filed with the IRS that the proposed rules "raise serious constitutional and legal issues" for social welfare nonprofits. These organizations have become known as "dark money" groups, because they allow political operatives to spend money on electoral activity without having to disclose donors.</p>

    <p>Colbert in 2011 ran segments on his Comedy Central show "The Colbert Report" exposing campaign finance absurdities through the creation of his own super PAC -- Americans for a Better Tomorrow, Tomorrow -- and a social welfare nonprofit. The Huffington Post ran a five-part series on Colbert's campaign finance exploits.</p>

    <p>Colbert officially retired his super PAC in 2012 and donated the funds raised by both organizations to two campaign finance watchdog groups, the Campaign Legal Center, founded by Colbert's lawyer Trevor Potter, and the Center for Responsive Politics.</p>

    <p>The proposed rules have attracted a whopping 143,635 comments to the IRS, with both tea party and progressive groups mobilizing supporters. Campaign finance reform supporters also have flooded the IRS with comments urging it to set a stringent and clear limit on the amount of electoral activity these groups are allowed. The Huffington Post previously examined the regulations here.</p>

    <p>Colbert's position on the lengthy and complicated proposed rules is not entirely clear. His letter simply states, "The Proposed Regulations raise serious constitutional and legal issues for Colbert Super PAC SHH Institute and other entities like it, which seek to make America a better place. I request the opportunity to discuss these issues in detail through oral testimony at a public hearing related to the Proposed Regulations."</p>
  </section>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>